### ISSUE TITLE
Settings page and related change password page bugs

### ISSUE THREAD

**Issue by amyzhaosicong** [mithunkumarnallu/ITWS6961-Group10#10]
1. Back-end of update user profile function all works now. 
2. Alert twice after update success, need to be fixed.
3. Need call back or some function after update success, the button now just disabled, need to be fixed.
4. Back-end of update password still working, should be done till this weekend.

**Comment by amyzhaosicong** [comment]
Fixed Q2 and Q3, alert only once after update success now. 
Redirected to settings page after alert, Q3 fixed.
Back-end of password still working now.

**Comment by amyzhaosicong** [comment]
Back-end of password finished and passed testing now.
Front-end of password also tested.

**Comment by nachi1490** [comment]
Settings page does not use Render template, some items of sidebar missing

**Comment by amyzhaosicong** [comment]
Thanks! I tried using render template but still not working in settings change password page. Working on it now.

**Comment by peiliangz** [comment]
fix it.
