### ISSUE TITLE
Login bugs

### ISSUE THREAD

**Issue by nitish661401869** [mithunkumarnallu/ITWS6961-Group10#12]
If user is not verified (has not clicked verification email link) and tries to sign in, do not sign him in and redirect check email confirmation page.

If user is logged in and redirects to login view...send him to the dashboard view instead.

**Comment by mithunkumarnallu** [comment]
If user is not verified (has not clicked verification email link) and tries to sign in, show an error message on the login page itself saying that the email is not yet verified.
Dont redirect him to the confirmation page.

**Comment by nitish661401869** [comment]
Issue Resolved: Commit #  ce6fa3ad2f7234562dc09a30d6f46144efb450e4
