### ISSUE TITLE
some test

### ISSUE THREAD

**Issue by peiliangz** [mithunkumarnallu/ITWS6961-Group10#27]
1. When a new tenant is added to an existent house, the rental payment did not decrease by half as expected.
2. Click on the "current house" tab on the right up corner, nothing happens, don't know if the hyper link is necessary.
3. When a tenant add another house which is close to other existent house, in the manage home page, it could only show the default housing location unless you zoom in the map. But this is a minor issue.

**Comment by mithunkumarnallu** [comment]
1. This works and noted as a misunderstanding
2. That's a valid issue but, no action on fixing it since its very minor
3. This is how the navigation between homes happen as of now. So, eventhough it has usability issues, closing it since there is little time to fix it.

Hence, Closing this ticket
